### ISSUE TITLE
ZerosLike error for Conv2D and ConvLSTM2D layers.

### ISSUE THREAD

**Issue by erdem-kose** [microsoft/tensorflow-directml-plugin#260]
```python
Node: 'Adam/gradients/zeros_like_6'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  ZerosLike with the variant data type is not yet supported for pluggable devices in this version of TensorFlow.
	 [[{{node Adam/gradients/zeros_like_6}}]]
	 [[gradient_tape/SeismicFourier/conv_lstm2d_1/TensorArrayUnstack/Shape/_168]]
  (1) INVALID_ARGUMENT:  ZerosLike with the variant data type is not yet supported for pluggable devices in this version of TensorFlow.
	 [[{{node Adam/gradients/zeros_like_6}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_8553]
```

I am receiving these errors when using 
plugin 0.0.1.dev220621
tensorflow-cpu 2.9.0

**Comment by erdem-kose** [comment]
it is only for ConvLSTM2D

**Comment by PatriceVignola** [comment]
Hi @erdem-kose! We already fixed this internally but haven't published a new package to pypi yet. We are planning to release a package in the next few weeks, shortly after the TensorFlow 2.10 release. In the meantime, you can try out our [nightly package](https://github.com/microsoft/tensorflow-directml-plugin/actions/runs/2953772219) and see if it fixes the issue for you.

**Comment by erdem-kose** [comment]
Will try, thanks.

**Comment by erdem-kose** [comment]
it worked, but there are performance issues I think,
thanks.

**Comment by PatriceVignola** [comment]
Yes, we are aware of performance issues for LSTM and RNN models. So far we have been focusing on closing the feature gap with `tensorflow-directml==1.15` and CNN model performance, but going forward we'll have more time to spend on optimization and closing the performance gap with CUDA.

Which model are you getting performance issues with? Maybe it's something that we can look at.

**Comment by erdem-kose** [comment]
I am using 2 ConvLSTM2D layers, but I will look at that and try to write exact issue.

**Comment by erdem-kose** [comment]
I used one of the latest builds, it is working well, no problem appeared, thanks.
I am closing the issue now.
