### ISSUE TITLE
Automatically downloading tensorflow-cpu==2.11.0

### ISSUE THREAD

**Issue by sabbir2609** [microsoft/tensorflow-directml-plugin#329]
TensorFlow DirectML Plugin only works with the `tensorflow-cpu>=2.10` but when I run pip `install tensorflow-directml-plugin`. It automatically downloads `tensorflow-cpu==2.11.0`.

**Comment by fortunewalla** [comment]
does it work with `2.11`? Do you get any error if you execute some of the sample GPU code?

**Comment by sabbir2609** [comment]
TF drooped native support for windows from v2.11.

**Comment by fortunewalla** [comment]
> TF drooped native support for windows from v2.11.

Yes. I too am using DML with version 2.10 but was wondering if DML in 2.11 works for your system.
