### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow-directml-plugin (from versions: none)

### ISSUE THREAD

**Issue by Swaggy23** [microsoft/tensorflow-directml-plugin#358]
ERROR: Could not find a version that satisfies the requirement tensorflow-directml-plugin (from versions: none when i try to install

**Comment by NateAGeek** [comment]
Same here...

**Comment by mmalek06** [comment]
And here...

**Comment by maggie1059** [comment]
Hi @Swaggy23, @NateAGeek, @mmalek06,
Are you seeing this when installing the plugin from PyPI (i.e. `pip install tensorflow-directml-plugin`) in a clean environment? I'm unable to repro this locally-- if anyone has output/error logs they can share with more info I can take a look!

**Comment by NateAGeek** [comment]
I think it is due to using Python 3.11, I ended up using the current PR for updating the versioning and it worked.

**Comment by maggie1059** [comment]
Thanks for the update @NateAGeek! Python 3.11 support was added for TF 2.12, which isn't in the official PyPI release for our plugin yet, so if anyone else was using a python 3.11 environment, please switch to python 3.7-3.10 until the next version of the plugin is released.
