### ISSUE TITLE
Adding a new device

### ISSUE THREAD

**Issue by RoySegal** [microsoft/tensorflow-directml-plugin#363]
Hi,
I am intreseted to find out what I need to do to add a new accelerator under DirectML.
I noticed that it currently supports Direct3D (DirectX12 devices) - which means GPUs only.
However, this accelerator isn't related to display and doesn't support DirectX12 framework.
What is the roadmap regarding adding support to non-display (non-GPU) hardware for DirectML?
Is there any way to integrate my accelerator into DirectML at the moment?

Thanks,
Roy

**Comment by PatriceVignola** [comment]
DirectML only supports DirectX 12 devices, and there aren't any plans to support other accelerators.
